### ISSUE TITLE
Development Environment 1.4.4 fails on Windows Pro

### ISSUE THREAD

**Issue by gitshub** [jburse/jekejeke-devel#19]
Hi, 
Not knowing much about Java, I can't figure out why "toplevel.jar" (part of "Development Environment 1.4.4, Evaluation License, English and German, Swing 1.6") under "Windows 10 Pro" fails, and I hope you can help.
My Java version is "
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)".

Here is the "Powershell" session:

PS C:\Users\artsa\Downloads\jekejeke\desktop> java -jar "toplevel.jar"
Exception in thread "main" java.lang.ExceptionInInitializerError
        at matula.platform.a.b.<init>(Unknown Source)
        at matula.platform.a.b.<clinit>(Unknown Source)
        at jekdev.platform.headless.a.createFoyer(Unknown Source)
        at jekpro.tools.term.Lobby.<init>(Unknown Source)
        at jekpro.tools.term.Knowledgebase.<init>(Unknown Source)
        at jekpro.util.d.a.a(Unknown Source)
        at omonia.util.b.a.b(Unknown Source)
        at omonia.util.b.a.F(Unknown Source)
        at omonia.util.b.l.setEnvironment(Unknown Source)
        at jekdev.platform.a.a.setEnvironment(Unknown Source)
        at jekpro.util.d.b.a(Unknown Source)
        at jekdev.platform.a.a.main(Unknown Source)
        at jekdev.platform.headless.ToolkitEnvironment.main(Unknown Source)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final jdk.internal.loader.URLClassPath jdk.internal.loader.BuiltinClassLoader.ucp accessible: module java.base does not "opens jdk.internal.loader" to unnamed module @5c671d7f
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:170)
        at matula.util.swing.RuntimeHotspot.<clinit>(Unknown Source)
        ... 13 more

By the way, the same file runs fine under Linux using java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09). Thanks.

**Comment by jburse** [comment]
For JDK >9 you need these command line options:

--add-opens java.base/jdk.internal.loader=ALL-UNNAMED

See also:
http://www.jekejeke.ch/idatab/doclet/prod/en/docs/05_run/10_docu/04_installation/11_library/01_swing/01_versions.html

This is only documented for the runtime library, but also applies for the development environment.

**Comment by gitshub** [comment]
Great-I'm in business!  Thanks for your quick reply.
